config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, :dependent => :delete_all
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true, uniqueness: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5]}, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render "new"
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    # we need @restaurant in our `simple_form_for`
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to asssociate review with corresponding restaurant
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    if @review.save
      redirect_to restaurant_path(@review.restaurant)
    else
      render 'new'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form_restaurant.html.erb
<%= form_for @restaurant do |t| %>
  <div class="form-group">
  <%= t.label :name, 'Name' %>
  <%= t.text_area :name, class: "form-control" %>
  </div>

  <div class="form-group">
  <%= t.label :category, 'Category' %>
  <%= t.text_area :category, class: "form-control" %>
  </div>

  <div class="form-group">
  <%= t.label :address, 'Address' %>
  <%= t.text_area :address, class: "form-control" %>
  </div>


  <div class="form-group">
  <%= t.label :phone_number, 'Phone_number' %>
  <%= t.text_area :phone_number, class: "form-control" %>
  </div>

  <%= t.submit class: 'btn btn-primary text-center' %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

app/views/restaurants/index.html.erb
<div class="text-center">
<h3>Restaurants</h3>
<% @restaurants.each do |restaurant| %>
  <h4> <%= link_to 'ℹ', restaurant_path(restaurant)%> <%= restaurant.name %> - <%= restaurant.category %> <%= link_to '🗑', restaurant_path(restaurant), method: :delete %></h4>
<% end %>
<%= link_to 'Create ➕', new_restaurant_path %>
</div>

app/views/restaurants/new.html.erb
<%= render 'form' %>

app/views/restaurants/show.html.erb
<div class="text-center">
  <h4> 🍽 <%= @restaurant.name %> - <%= @restaurant.category %> </h4>
  <h5>📍<%= @restaurant.address %></h5>
  <h5> ☎️ <%= @restaurant.phone_number %></h5>
  <p><% @restaurant.reviews.each do |review| %>
    <p>🖋 <%= review.content%>  -  <%= '⭐️' * review.rating %></p>
    <% end %>
  </p>

  <%= link_to 'Back 🏠', restaurants_path %> <%= link_to 'Edit 🔩', edit_restaurant_path(@restaurant) %> <%= link_to 'Add a Review➕',  new_restaurant_review_path(@restaurant) %>
</div>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>